### ISSUE TITLE
Users complain about NG soldiers HP

### ISSUE THREAD

**Issue by Lunreth** [dysphie/nmrih-hitbox-dmg-fix#1]
As a suggestion, consider adding a Cvar to change amount of hits required to kill a NG soldier, or just a % of damage reduction related to their armor (head and/or body)

**Comment by dysphie** [comment]
Such cvars already exist in game (`sv_helmet_scale_dmg`, `sv_armor_scale_dmg`, `sv_helmet_scale_rifle_dmg`). Closing
